# XGBoost Model - Hyperparameter Optimization

In [75]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import torch

from optuna.visualization import plot_contour
from optuna.visualization import plot_edf
from optuna.visualization import plot_intermediate_values
from optuna.visualization import plot_optimization_history
from optuna.visualization import plot_parallel_coordinate
from optuna.visualization import plot_param_importances
from optuna.visualization import plot_rank
from optuna.visualization import plot_slice
from optuna.visualization import plot_timeline

### Data Loading

In [76]:
# Load the data
train_x_df = pd.read_csv('../../data/X_train.csv')
train_y_df = pd.read_csv('../../data/Y_train.csv')

test_x_df = pd.read_csv('../../data/X_test.csv')

C:\Users\tomhi\AppData\Local\Temp\ipykernel_22292\3151947916.py:2: DtypeWarning: Columns (0: item21, 1: item22, 2: item23, 3: item24, 4: make21, 5: make22, 6: make23, 7: make24, 8: model21, 9: model22, 10: model23, 11: model24, 12: goods_code1, 13: goods_code8, 14: goods_code9, 15: goods_code10, 16: goods_code11, 17: goods_code12, 18: goods_code13, 19: goods_code14, 20: goods_code15, 21: goods_code16, 22: goods_code17, 23: goods_code18, 24: goods_code19, 25: goods_code20, 26: goods_code21, 27: goods_code22, 28: goods_code23, 29: goods_code24) have mixed types. Specify dtype option on import or set low_memory=False.
  train_x_df = pd.read_csv('../../data/X_train.csv')
C:\Users\tomhi\AppData\Local\Temp\ipykernel_22292\3151947916.py:5: DtypeWarning: Columns (0: item20, 1: item21, 2: item22, 3: item23, 4: item24, 5: make20, 6: make21, 7: make22, 8: make23, 9: make24, 10: model20, 11: model21, 12: model22, 13: model23, 14: model24, 15: goods_code1, 16: goods_code10, 17: goods_code11, 18: goods_code12, 19: goods_code13, 20: goods_code14, 21: goods_code15, 22: goods_code16, 23: goods_code17, 24: goods_code18, 25: goods_code19, 26: goods_code20, 27: goods_code21, 28: goods_code22) have mixed types. Specify dtype option on import or set low_memory=False.
  test_x_df = pd.read_csv('../../data/X_test.csv')

### Get Categorical features

In [77]:
item_cols = [f'item{i}' for i in range(1, 25)]
make_cols = [f'make{i}' for i in range(1, 25)]
goods_cols = [f'goods_code{i}' for i in range(1, 25)]

cat_cols = item_cols + make_cols + goods_cols

print(cat_cols)

train_x_df[cat_cols].head()

['item1', 'item2', 'item3', 'item4', 'item5', 'item6', 'item7', 'item8', 'item9', 'item10', 'item11', 'item12', 'item13', 'item14', 'item15', 'item16', 'item17', 'item18', 'item19', 'item20', 'item21', 'item22', 'item23', 'item24', 'make1', 'make2', 'make3', 'make4', 'make5', 'make6', 'make7', 'make8', 'make9', 'make10', 'make11', 'make12', 'make13', 'make14', 'make15', 'make16', 'make17', 'make18', 'make19', 'make20', 'make21', 'make22', 'make23', 'make24', 'goods_code1', 'goods_code2', 'goods_code3', 'goods_code4', 'goods_code5', 'goods_code6', 'goods_code7', 'goods_code8', 'goods_code9', 'goods_code10', 'goods_code11', 'goods_code12', 'goods_code13', 'goods_code14', 'goods_code15', 'goods_code16', 'goods_code17', 'goods_code18', 'goods_code19', 'goods_code20', 'goods_code21', 'goods_code22', 'goods_code23', 'goods_code24']

,item1,item2,item3,item4,item5,item6,item7,item8,item9,item10,...,goods_code15,goods_code16,goods_code17,goods_code18,goods_code19,goods_code20,goods_code21,goods_code22,goods_code23,goods_code24
0,COMPUTERS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,COMPUTER PERIPHERALS ACCESSORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,COMPUTERS,COMPUTER PERIPHERALS ACCESSORIES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TELEVISIONS HOME CINEMA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Fill NaN values with a flag string

In [78]:
train_x_df[cat_cols] = train_x_df[cat_cols].fillna("NONE")
test_x_df[cat_cols] = test_x_df[cat_cols].fillna("NONE")

train_x_df[cat_cols].head()

,item1,item2,item3,item4,item5,item6,item7,item8,item9,item10,...,goods_code15,goods_code16,goods_code17,goods_code18,goods_code19,goods_code20,goods_code21,goods_code22,goods_code23,goods_code24
0,COMPUTERS,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
1,COMPUTER PERIPHERALS ACCESSORIES,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
2,TELEVISIONS HOME CINEMA,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
3,COMPUTERS,COMPUTER PERIPHERALS ACCESSORIES,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE
4,TELEVISIONS HOME CINEMA,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,...,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE

### Create vocabulary for each type of category (string to number mapping)

In [79]:
def create_shared_vocab(train_df, test_df, cols):

    all_values = pd.concat([
        train_df[col]
        for col in cols
    ] + [
        test_df[col]
        for col in cols
    ]).astype(str)

    unique_values = sorted(
        set(all_values) - {"NONE"}
    )

    vocab = {
        value: idx + 1
        for idx, value in enumerate(unique_values)
    }

    vocab["NONE"] = 0

    return vocab

item_vocab = create_shared_vocab(
    train_x_df,
    test_x_df,
    item_cols
)

make_vocab = create_shared_vocab(
    train_x_df,
    test_x_df,
    make_cols
)

goods_vocab = create_shared_vocab(
    train_x_df,
    test_x_df,
    goods_cols
)

print(item_vocab)

{'2HP ELITEBOOK 850V6': 1, '2LOGITECH PEBBLE M350 BLUETOOTH MOUSE': 2, '2MICROSOFT OFFICE HOME AND STUDENT 2019,': 3, '2TARGUS GEOLITE ESSENTIAL CASE': 4, '2TOSHIBA PORTABLE HARD DRIVE': 5, '6  SPACE GREY 32GB': 6, 'AERIALS REMOTE CONTROLS': 7, 'APPLE PRODUCTDESCRIPTION': 8, 'APPLE S': 9, 'AUDIO ACCESSORIES': 10, 'BABY & CHILD TRAVEL': 11, 'BABY CHANGING': 12, 'BABY CHILD TRAVEL': 13, 'BABY FEEDING': 14, 'BABY PLAY EQUIPMENT': 15, 'BABYWEAR': 16, 'BAGS & CARRY CASES': 17, 'BAGS CARRY CASES': 18, 'BAGS WALLETS ACCESSORIES': 19, 'BAGS, WALLETS & ACCESSORIES': 20, 'BARBECUES & ACCESSORIES': 21, 'BARBECUES ACCESSORIES': 22, 'BARWARE': 23, 'BATH & BODYCARE': 24, 'BATH BODYCARE': 25, 'BATH LINEN': 26, 'BATHROOM': 27, 'BATHROOM ACCESSORIES': 28, 'BATHROOM FIXTURES': 29, 'BED LINEN': 30, 'BEDROOM FURNITURE': 31, 'BLANK MEDIA & MEDIA STORAGE': 32, 'BLANK MEDIA MEDIA STORAGE': 33, 'BOOKS': 34, 'BOYSWEAR': 35, 'CABLES & ADAPTERS': 36, 'CABLES ADAPTERS': 37, 'CARPETS RUGS FLOORING': 38, 'CARPETS, RUGS & FLOORING': 39, 'CHILDREN S ACCESSORIES': 40, 'CHILDREN S FOOTWEAR': 41, 'CHILDREN S FURNITURE': 42, 'CHILDRENS FOOTWEAR': 43, 'CHRISTMAS DECORATIONS': 44, 'COMPUTER NETWORKING': 45, 'COMPUTER PERIPHERALS & ACCESSORIES': 46, 'COMPUTER PERIPHERALS ACCESSORIES': 47, 'COMPUTER SOFTWARE': 48, 'COMPUTERS': 49, 'COOKING APPLIANCES': 50, 'COOKWARE': 51, 'CRAFT': 52, 'DECORATING': 53, 'DECORATIVE ACCESSORIES': 54, 'DIARIES & ORGANISERS': 55, 'DIARIES ORGANISERS': 56, 'DISPOSABLE TABLEWARE CUTLERY': 57, 'DOOR FURNITURE': 58, 'DRESSMAKING': 59, 'EASTER DECORATIONS': 60, 'FACIAL SKINCARE': 61, 'FILING & DESK ACCESSORIES': 62, 'FILING DESK ACCESSORIES': 63, 'FITTED KITCHENS': 64, 'FOOD PREPARATION': 65, 'FOOD STORAGE': 66, 'FRAGRANCE': 67, 'FULFILMENT CHARGE': 68, 'GAMES': 69, 'GAMING': 70, 'GARDENING EQUIPMENT': 71, 'GIFT FOOD DRINK': 72, 'GIFT WRAP': 73, 'GIRLSWEAR': 74, 'GREETING CARDS & PERSONALISED STATIONERY': 75, 'GREETING CARDS PERSONALISED STATIONERY': 76, 'GYM EQUIPMENT': 77, 'HAIRCARE': 78, 'HEALTH & BEAUTY ELECTRICAL': 79, 'HEALTH BEAUTY ACCESSORIES': 80, 'HEALTH BEAUTY ELECTRICAL': 81, 'HEATING & COOLING APPLIANCES': 82, 'HEATING COOLING APPLIANCES': 83, 'HI-FI': 84, 'HOME AND PERSONAL SECURITY': 85, 'HOME OFFICE': 86, 'HOME SAFETY EQUIPMENT': 87, 'HOT DRINK PREPARATION': 88, 'HOUSEHOLD CLEANING': 89, 'HP ELITEBOOK 850V6': 90, 'IMAGING ACCESSORIES': 91, 'IMAGING EQUIPMENT': 92, 'JEWELLERY & WATCHES': 93, 'JEWELLERY WATCHES': 94, 'KITCHEN ACCESSORIES': 95, 'KITCHEN SCALES & MEASURES': 96, 'KITCHEN SCALES MEASURES': 97, 'KITCHEN STORAGE': 98, 'KITCHEN UTENSILS & GADGETS': 99, 'KITCHEN UTENSILS GADGETS': 100, 'LAUNDRY & CLOTHESCARE': 101, 'LAUNDRY APPLIANCES': 102, 'LAUNDRY CLOTHESCARE': 103, 'LIGHTING': 104, 'LINGERIE & HOISERY': 105, 'LINGERIE HOISERY': 106, 'LIVING & DINING FURNITURE': 107, 'LIVING DINING FURNITURE': 108, 'LOGITECH PEBBLE M350 BLUETOOTH MOUSE': 109, 'LUGGAGE': 110, 'MAKEUP': 111, 'MEN S ACCESSORIES': 112, 'MEN S CLOTHES': 113, 'MEN S FOOTWEAR': 114, 'MEN S NIGHTWEAR': 115, 'MEN S SPORTSWEAR': 116, 'MEN S UNDERWEAR SOCKS': 117, 'MENS CLOTHES': 118, 'MENS NIGHTWEAR': 119, 'MENS UNDERWEAR & SOCKS': 120, 'MICROSOFT OFFICE HOME AND STUDENT 2019,': 121, 'NURSERY ACCESSORIES': 122, 'NURSERY EQUIPMENT FURNITURE': 123, 'NURSERY FURNITURE': 124, 'NURSERY LINEN': 125, 'NURSERY TOYS': 126, 'OUTDOOR ACCESSORIES': 127, 'OUTDOOR FURNITURE': 128, 'PAPER & NOTEBOOKS': 129, 'PAPER NOTEBOOKS': 130, 'PARTY DECORATIONS': 131, 'PENS PENCILS': 132, 'PICNICWARE': 133, 'PORTABLE AUDIO EQUIPMENT': 134, 'POWER & BATTERIES': 135, 'POWER BATTERIES': 136, 'PRESERVING & BAKING EQUIPMENT': 137, 'PRESERVING BAKING EQUIPMENT': 138, 'PRINTERS & SCANNERS': 139, 'PRINTERS SCANNERS': 140, 'PRODUCT': 141, 'SCHOOLWEAR': 142, 'SERVICE': 143, 'SOFT FURNISHINGS': 144, 'SPORTS EQUIPMENT': 145, 'STANDS & BRACKETS': 146, 'STANDS BRACKETS': 147, 'STATIONERY SUNDRIES': 148, 'STORAGE & ORGANISATION': 149, 'STORAGE ORGANISATION': 150, 'SUNCARE': 151, 'SUNGLASSES & READING GLASSES': 152, 'SUNGLASSES READING GLASSES': 153, 'TABLE LINEN': 154, 'TABLEWARE': 155, 'TARGUS GEOLITE ESSENTIAL CASE': 156, 'TECHNOLOGY ACCESSORIES': 157, 'TELEPHONE ACCESSORIES': 158, 'TELEPHONES FAX MACHINES TWO-WAY RADIOS': 159, 'TELEPHONES, FAX MACHINES & TWO-WAY RADIOS': 160, 'TELEVISIONS & HOME CINEMA': 161, 'TELEVISIONS HOME CINEMA': 162, 'THEMED GIFTS': 163, 'TOSHIBA PORTABLE HARD DRIVE': 164, 'TOYS': 165, 'UNKNOWN': 166, 'VIDEOS DVD DIGITAL EQUIPMENT': 167, 'WARRANTY': 168, 'WINDOW DRESSING': 169, 'WOMEN S ACCESSORIES': 170, 'WOMEN S CLOTHES': 171, 'WOMEN S FOOTWEAR': 172, 'WOMEN S NIGHTWEAR': 173, 'WOMENS ACCESSORIES': 174, 'WOMENS CLOTHES': 175, 'WOMENS FOOTWEAR': 176, 'WOMENS NIGHTWEAR': 177, 'NONE': 0}

### Encode all categorical columns using the vocabs

In [80]:
def encode_columns(df, cols, vocab):

    for col in cols:

        df[col] = (
            df[col]
            .astype(str)
            .map(vocab)
            .fillna(0)
            .astype(int)
        )

encode_columns(train_x_df,item_cols,item_vocab)
encode_columns(test_x_df,item_cols,item_vocab)
encode_columns(train_x_df,make_cols,make_vocab)
encode_columns(test_x_df,make_cols,make_vocab)
encode_columns(train_x_df,goods_cols,goods_vocab)
encode_columns(test_x_df,goods_cols,goods_vocab)

train_x_df[cat_cols].head()

,item1,item2,item3,item4,item5,item6,item7,item8,item9,item10,...,goods_code15,goods_code16,goods_code17,goods_code18,goods_code19,goods_code20,goods_code21,goods_code22,goods_code23,goods_code24
0,49,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,47,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,162,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,49,47,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,162,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [81]:
embedding_sizes = {
    "item": len(item_vocab),
    "make": len(make_vocab),
    "goods": len(goods_vocab)
}

print(embedding_sizes)

{'item': 178, 'make': 888, 'goods': 17029}

### Identify and clean numeric columns (replace NaN with 0)

In [82]:
# Identify numeric columns
numeric_cols = [
    col for col in train_x_df.columns
    if col not in cat_cols + ['ID'] + ['Nb_of_items'] + ['model' + str(i) for i in range(1, 25)]
]

print(numeric_cols)

train_x_df[numeric_cols].head()

['cash_price1', 'cash_price2', 'cash_price3', 'cash_price4', 'cash_price5', 'cash_price6', 'cash_price7', 'cash_price8', 'cash_price9', 'cash_price10', 'cash_price11', 'cash_price12', 'cash_price13', 'cash_price14', 'cash_price15', 'cash_price16', 'cash_price17', 'cash_price18', 'cash_price19', 'cash_price20', 'cash_price21', 'cash_price22', 'cash_price23', 'cash_price24', 'Nbr_of_prod_purchas1', 'Nbr_of_prod_purchas2', 'Nbr_of_prod_purchas3', 'Nbr_of_prod_purchas4', 'Nbr_of_prod_purchas5', 'Nbr_of_prod_purchas6', 'Nbr_of_prod_purchas7', 'Nbr_of_prod_purchas8', 'Nbr_of_prod_purchas9', 'Nbr_of_prod_purchas10', 'Nbr_of_prod_purchas11', 'Nbr_of_prod_purchas12', 'Nbr_of_prod_purchas13', 'Nbr_of_prod_purchas14', 'Nbr_of_prod_purchas15', 'Nbr_of_prod_purchas16', 'Nbr_of_prod_purchas17', 'Nbr_of_prod_purchas18', 'Nbr_of_prod_purchas19', 'Nbr_of_prod_purchas20', 'Nbr_of_prod_purchas21', 'Nbr_of_prod_purchas22', 'Nbr_of_prod_purchas23', 'Nbr_of_prod_purchas24']

,cash_price1,cash_price2,cash_price3,cash_price4,cash_price5,cash_price6,cash_price7,cash_price8,cash_price9,cash_price10,...,Nbr_of_prod_purchas15,Nbr_of_prod_purchas16,Nbr_of_prod_purchas17,Nbr_of_prod_purchas18,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24
0,889.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,409.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1399.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,689.0,119.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1199.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
# Clean numberic columns by converting to numeric and filling NaNs with 0
train_x_df[numeric_cols] = train_x_df[numeric_cols].apply(pd.to_numeric, errors="coerce").fillna(0)
test_x_df[numeric_cols] = test_x_df[numeric_cols].apply(pd.to_numeric, errors="coerce").fillna(0)

train_x_df[numeric_cols].head()

,cash_price1,cash_price2,cash_price3,cash_price4,cash_price5,cash_price6,cash_price7,cash_price8,cash_price9,cash_price10,...,Nbr_of_prod_purchas15,Nbr_of_prod_purchas16,Nbr_of_prod_purchas17,Nbr_of_prod_purchas18,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24
0,889.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,409.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1399.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,689.0,119.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1199.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### Add aggregated numeric values (like average item price)

In [84]:
qty_cols = [f'Nbr_of_prod_purchas{i}' for i in range(1, 25)]

price_cols = [f'cash_price{i}' for i in range(1, 25)]

train_x_df['total_item_count'] = train_x_df[qty_cols].sum(axis=1)
train_x_df['total_price'] = train_x_df[price_cols].sum(axis=1)
train_x_df['max_price'] = train_x_df[price_cols].max(axis=1)
train_x_df['mean_price'] = train_x_df[price_cols].sum(axis=1) / train_x_df['total_item_count']

test_x_df['total_item_count'] = test_x_df[qty_cols].sum(axis=1)
test_x_df['total_price'] = test_x_df[price_cols].sum(axis=1)
test_x_df['max_price'] = test_x_df[price_cols].max(axis=1)
test_x_df['mean_price'] = test_x_df[price_cols].sum(axis=1) / test_x_df['total_item_count']

# Refresh numeric cols list to include new features
numeric_cols = [
    col for col in train_x_df.columns
    if col not in cat_cols + ['ID'] + ['Nb_of_items'] + ['model' + str(i) for i in range(1, 25)]
]

print(numeric_cols)

train_x_df[numeric_cols].head()

['cash_price1', 'cash_price2', 'cash_price3', 'cash_price4', 'cash_price5', 'cash_price6', 'cash_price7', 'cash_price8', 'cash_price9', 'cash_price10', 'cash_price11', 'cash_price12', 'cash_price13', 'cash_price14', 'cash_price15', 'cash_price16', 'cash_price17', 'cash_price18', 'cash_price19', 'cash_price20', 'cash_price21', 'cash_price22', 'cash_price23', 'cash_price24', 'Nbr_of_prod_purchas1', 'Nbr_of_prod_purchas2', 'Nbr_of_prod_purchas3', 'Nbr_of_prod_purchas4', 'Nbr_of_prod_purchas5', 'Nbr_of_prod_purchas6', 'Nbr_of_prod_purchas7', 'Nbr_of_prod_purchas8', 'Nbr_of_prod_purchas9', 'Nbr_of_prod_purchas10', 'Nbr_of_prod_purchas11', 'Nbr_of_prod_purchas12', 'Nbr_of_prod_purchas13', 'Nbr_of_prod_purchas14', 'Nbr_of_prod_purchas15', 'Nbr_of_prod_purchas16', 'Nbr_of_prod_purchas17', 'Nbr_of_prod_purchas18', 'Nbr_of_prod_purchas19', 'Nbr_of_prod_purchas20', 'Nbr_of_prod_purchas21', 'Nbr_of_prod_purchas22', 'Nbr_of_prod_purchas23', 'Nbr_of_prod_purchas24', 'total_item_count', 'total_price', 'max_price', 'mean_price']

C:\Users\tomhi\AppData\Local\Temp\ipykernel_22292\3222992749.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['total_item_count'] = train_x_df[qty_cols].sum(axis=1)
C:\Users\tomhi\AppData\Local\Temp\ipykernel_22292\3222992749.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['total_price'] = train_x_df[price_cols].sum(axis=1)
C:\Users\tomhi\AppData\Local\Temp\ipykernel_22292\3222992749.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['max_price'] = train_x_df[price_cols].max(axis=1)
C:\Users\tomhi\AppData\Local\Temp\ipykernel_22292\3222992749.py:8: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  train_x_df['mean_price'] = train_x_df[price_cols].sum(axis=1) / train_x_df['total_item_count']
C:\Users\tomhi\AppData\Local\Temp\ipykernel_22292\3222992749.py:10: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['total_item_count'] = test_x_df[qty_cols].sum(axis=1)
C:\Users\tomhi\AppData\Local\Temp\ipykernel_22292\3222992749.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['total_price'] = test_x_df[price_cols].sum(axis=1)
C:\Users\tomhi\AppData\Local\Temp\ipykernel_22292\3222992749.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['max_price'] = test_x_df[price_cols].max(axis=1)
C:\Users\tomhi\AppData\Local\Temp\ipykernel_22292\3222992749.py:13: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  test_x_df['mean_price'] = test_x_df[price_cols].sum(axis=1) / test_x_df['total_item_count']

,cash_price1,cash_price2,cash_price3,cash_price4,cash_price5,cash_price6,cash_price7,cash_price8,cash_price9,cash_price10,...,Nbr_of_prod_purchas19,Nbr_of_prod_purchas20,Nbr_of_prod_purchas21,Nbr_of_prod_purchas22,Nbr_of_prod_purchas23,Nbr_of_prod_purchas24,total_item_count,total_price,max_price,mean_price
0,889.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,889.0,889.0,889.0
1,409.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,409.0,409.0,409.0
2,1399.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1399.0,1399.0,1399.0
3,689.0,119.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2.0,808.0,689.0,404.0
4,1199.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1199.0,1199.0,1199.0

### Convert to Tensors

In [85]:
import torch

X_cat = torch.tensor(
    train_x_df[cat_cols].values,
    dtype=torch.long
)

X_cat_test = torch.tensor(
    test_x_df[cat_cols].values,
    dtype=torch.long
)

X_num = torch.tensor(
    train_x_df[numeric_cols].values,
    dtype=torch.float32
)

X_num_test = torch.tensor(
    test_x_df[numeric_cols].values,
    dtype=torch.float32
)

y = train_y_df["fraud_flag"].values

y_tensor = torch.tensor(
    y,
    dtype=torch.float32
)

print(X_cat.shape)
print(X_num.shape)
print(y_tensor.shape)

print(X_cat[:1])
print(X_num[:1])

torch.Size([92790, 72])
torch.Size([92790, 52])
torch.Size([92790])
tensor([[   49,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,    34,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0, 12760,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
             0,     0]])
tensor([[889.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
           1., 889., 889., 889.]])

### Train / Validation Split

In [86]:
from sklearn.model_selection import train_test_split

X_cat_train, X_cat_val, X_num_train, X_num_val, y_train, y_val = train_test_split(
    X_cat, X_num, y_tensor, test_size=0.15, random_state=42
)

print(type(y_val))
print(np.shape(y_val))
print(y_val[:95])

<class 'torch.Tensor'>
torch.Size([13919])
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1.])

## Run Optuna Study

In [87]:
import optuna
from optuna.integration import XGBoostPruningCallback
from xgboost import XGBClassifier
from sklearn.metrics import average_precision_score
import numpy as np

N_TRIALS = 100

X_train_xgb = np.hstack([X_num_train.numpy(), X_cat_train.numpy()])
X_val_xgb   = np.hstack([X_num_val.numpy(),   X_cat_val.numpy()])
X_test_xgb  = np.hstack([X_num_test.numpy(),  X_cat_test.numpy()])

scale = (y_train.numpy() == 0).sum() / (y_train.numpy() == 1).sum()

def objective(trial):
    params = {
        'n_estimators':          trial.suggest_int('n_estimators', 500, 3000),
        'learning_rate':         trial.suggest_float('learning_rate', 0.02, 0.08, log=True),
        'max_depth':             trial.suggest_int('max_depth', 5, 10),
        'min_child_weight':      trial.suggest_int('min_child_weight', 1, 20),
        'subsample':             trial.suggest_float('subsample', 0.5, 1.0),
        'colsample_bytree':      trial.suggest_float('colsample_bytree', 0.3, 1.0),
        'gamma':                 trial.suggest_float('gamma', 0, 5),
        'scale_pos_weight':      scale,
        'eval_metric':           'aucpr',
        'early_stopping_rounds': 50,
        'random_state':          42,
        'callbacks':             [XGBoostPruningCallback(trial, 'validation_0-aucpr')],
    }
    model = XGBClassifier(**params)
    model.fit(
        X_train_xgb, y_train.numpy(),
        eval_set=[(X_val_xgb, y_val.numpy())],
        verbose=False
    )

    preds = model.predict_proba(X_val_xgb)[:, 1]
    score = average_precision_score(y_val.numpy(), preds)
    return score

pruner = optuna.pruners.MedianPruner(n_startup_trials=5, n_warmup_steps=100)

study = optuna.create_study(direction='maximize', pruner=pruner)
study.optimize(objective, n_trials=N_TRIALS, show_progress_bar=True)

print(f"Best Val PR-AUC: {study.best_value:.4f}")
print(f"Best params: {study.best_params}")

[I 2026-06-08 17:48:46,099] A new study created in memory with name: no-name-3b0cc5d7-2df1-499f-bc0b-53f9aae93119
Best trial: 0. Best value: 0.153984:   1%|          | 1/100 [00:11<19:01, 11.53s/it]

[I 2026-06-08 17:48:57,629] Trial 0 finished with value: 0.15398392492002244 and parameters: {'n_estimators': 2435, 'learning_rate': 0.04100869280370616, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.67676839321933, 'colsample_bytree': 0.5385957366319942, 'gamma': 4.30758741182088}. Best is trial 0 with value: 0.15398392492002244.

Best trial: 1. Best value: 0.164048:   2%|▏         | 2/100 [00:16<12:37,  7.73s/it]

[I 2026-06-08 17:49:02,701] Trial 1 finished with value: 0.1640476687479412 and parameters: {'n_estimators': 552, 'learning_rate': 0.04620263793157341, 'max_depth': 9, 'min_child_weight': 16, 'subsample': 0.9378453879558923, 'colsample_bytree': 0.58594400206982, 'gamma': 3.001406662503948}. Best is trial 1 with value: 0.1640476687479412.

Best trial: 1. Best value: 0.164048:   3%|▎         | 3/100 [00:23<12:00,  7.43s/it]

[I 2026-06-08 17:49:09,779] Trial 2 finished with value: 0.16318145868722816 and parameters: {'n_estimators': 961, 'learning_rate': 0.027863042004512943, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.7944276278635614, 'colsample_bytree': 0.5431729453752439, 'gamma': 3.5119406516447538}. Best is trial 1 with value: 0.1640476687479412.

Best trial: 1. Best value: 0.164048:   4%|▍         | 4/100 [00:29<11:05,  6.93s/it]

[I 2026-06-08 17:49:15,945] Trial 3 finished with value: 0.14871847386849946 and parameters: {'n_estimators': 1532, 'learning_rate': 0.03269931957377473, 'max_depth': 9, 'min_child_weight': 3, 'subsample': 0.7603787814379692, 'colsample_bytree': 0.8002284496909562, 'gamma': 0.788254111699776}. Best is trial 1 with value: 0.1640476687479412.

Best trial: 1. Best value: 0.164048:   5%|▌         | 5/100 [00:36<10:50,  6.85s/it]

[I 2026-06-08 17:49:22,640] Trial 4 finished with value: 0.14136126578976543 and parameters: {'n_estimators': 1333, 'learning_rate': 0.05131226249051094, 'max_depth': 5, 'min_child_weight': 20, 'subsample': 0.6015439759485511, 'colsample_bytree': 0.5522078195743187, 'gamma': 3.145919082005204}. Best is trial 1 with value: 0.1640476687479412.

Best trial: 1. Best value: 0.164048:   6%|▌         | 6/100 [00:39<08:34,  5.47s/it]

[I 2026-06-08 17:49:25,444] Trial 5 pruned. Trial was pruned at iteration 100.

Best trial: 1. Best value: 0.164048:   7%|▋         | 7/100 [00:42<07:14,  4.67s/it]

[I 2026-06-08 17:49:28,468] Trial 6 pruned. Trial was pruned at iteration 100.

Best trial: 1. Best value: 0.164048:   8%|▊         | 8/100 [00:44<06:04,  3.96s/it]

[I 2026-06-08 17:49:30,901] Trial 7 pruned. Trial was pruned at iteration 100.

Best trial: 1. Best value: 0.164048:   9%|▉         | 9/100 [00:47<05:19,  3.51s/it]

[I 2026-06-08 17:49:33,421] Trial 8 pruned. Trial was pruned at iteration 100.

Best trial: 1. Best value: 0.164048:  10%|█         | 10/100 [00:49<04:47,  3.19s/it]

[I 2026-06-08 17:49:35,893] Trial 9 pruned. Trial was pruned at iteration 100.

Best trial: 10. Best value: 0.169132:  11%|█         | 11/100 [00:58<07:09,  4.82s/it]

[I 2026-06-08 17:49:44,410] Trial 10 finished with value: 0.1691321376609136 and parameters: {'n_estimators': 533, 'learning_rate': 0.07533969441208284, 'max_depth': 10, 'min_child_weight': 16, 'subsample': 0.9639504713773154, 'colsample_bytree': 0.9298678331066315, 'gamma': 4.957047389228096}. Best is trial 10 with value: 0.1691321376609136.

Best trial: 10. Best value: 0.169132:  12%|█▏        | 12/100 [01:04<07:36,  5.18s/it]

[I 2026-06-08 17:49:50,422] Trial 11 finished with value: 0.162540632480922 and parameters: {'n_estimators': 556, 'learning_rate': 0.07924812210884288, 'max_depth': 10, 'min_child_weight': 16, 'subsample': 0.9996997345328121, 'colsample_bytree': 0.9727845499296883, 'gamma': 4.750307785292394}. Best is trial 10 with value: 0.1691321376609136.

Best trial: 10. Best value: 0.169132:  13%|█▎        | 13/100 [01:10<08:02,  5.54s/it]

[I 2026-06-08 17:49:56,799] Trial 12 finished with value: 0.16590279190996857 and parameters: {'n_estimators': 941, 'learning_rate': 0.07943934022417987, 'max_depth': 10, 'min_child_weight': 16, 'subsample': 0.9028113592256952, 'colsample_bytree': 0.8927301240850787, 'gamma': 3.143753370486118}. Best is trial 10 with value: 0.1691321376609136.

Best trial: 13. Best value: 0.172547:  14%|█▍        | 14/100 [01:20<09:40,  6.75s/it]

[I 2026-06-08 17:50:06,325] Trial 13 finished with value: 0.17254692511824377 and parameters: {'n_estimators': 1006, 'learning_rate': 0.07948074551816904, 'max_depth': 10, 'min_child_weight': 14, 'subsample': 0.8590292653679301, 'colsample_bytree': 0.9896789468381151, 'gamma': 4.999539107727588}. Best is trial 13 with value: 0.17254692511824377.

Best trial: 13. Best value: 0.172547:  15%|█▌        | 15/100 [01:27<09:36,  6.78s/it]

[I 2026-06-08 17:50:13,177] Trial 14 finished with value: 0.1689618609828513 and parameters: {'n_estimators': 1014, 'learning_rate': 0.06689009503809136, 'max_depth': 8, 'min_child_weight': 12, 'subsample': 0.8616100844997754, 'colsample_bytree': 0.98279810764219, 'gamma': 4.808765593093549}. Best is trial 13 with value: 0.17254692511824377.

Best trial: 13. Best value: 0.172547:  16%|█▌        | 16/100 [01:36<10:37,  7.59s/it]

[I 2026-06-08 17:50:22,649] Trial 15 finished with value: 0.16947320352648523 and parameters: {'n_estimators': 1917, 'learning_rate': 0.06570153089673456, 'max_depth': 10, 'min_child_weight': 18, 'subsample': 0.8471603116328886, 'colsample_bytree': 0.8658673288440835, 'gamma': 3.992245319258012}. Best is trial 13 with value: 0.17254692511824377.

Best trial: 13. Best value: 0.172547:  17%|█▋        | 17/100 [01:42<09:52,  7.13s/it]

[I 2026-06-08 17:50:28,723] Trial 16 pruned. Trial was pruned at iteration 100.

Best trial: 13. Best value: 0.172547:  18%|█▊        | 18/100 [01:48<09:24,  6.89s/it]

[I 2026-06-08 17:50:35,031] Trial 17 finished with value: 0.14298189857893487 and parameters: {'n_estimators': 1948, 'learning_rate': 0.02142673476835132, 'max_depth': 9, 'min_child_weight': 18, 'subsample': 0.8199555702529566, 'colsample_bytree': 0.7908724526811058, 'gamma': 3.8433604165983324}. Best is trial 13 with value: 0.17254692511824377.

Best trial: 13. Best value: 0.172547:  19%|█▉        | 19/100 [01:57<10:05,  7.48s/it]

[I 2026-06-08 17:50:43,891] Trial 18 pruned. Trial was pruned at iteration 100.

Best trial: 13. Best value: 0.172547:  20%|██        | 20/100 [02:04<09:41,  7.27s/it]

[I 2026-06-08 17:50:50,664] Trial 19 pruned. Trial was pruned at iteration 100.

Best trial: 13. Best value: 0.172547:  21%|██        | 21/100 [02:10<09:10,  6.96s/it]

[I 2026-06-08 17:50:56,914] Trial 20 pruned. Trial was pruned at iteration 100.

Best trial: 13. Best value: 0.172547:  22%|██▏       | 22/100 [02:17<08:50,  6.80s/it]

[I 2026-06-08 17:51:03,339] Trial 21 finished with value: 0.16260471036895116 and parameters: {'n_estimators': 1173, 'learning_rate': 0.07945144449988048, 'max_depth': 10, 'min_child_weight': 18, 'subsample': 0.9954267356418484, 'colsample_bytree': 0.9097342282810056, 'gamma': 4.985170695054663}. Best is trial 13 with value: 0.17254692511824377.

Best trial: 13. Best value: 0.172547:  23%|██▎       | 23/100 [02:37<14:05, 10.98s/it]

[I 2026-06-08 17:51:24,061] Trial 22 finished with value: 0.17094393998887192 and parameters: {'n_estimators': 1630, 'learning_rate': 0.06981042201012273, 'max_depth': 10, 'min_child_weight': 15, 'subsample': 0.9396504444301221, 'colsample_bytree': 0.9266618732848253, 'gamma': 4.533052941084865}. Best is trial 13 with value: 0.17254692511824377.

Best trial: 13. Best value: 0.172547:  24%|██▍       | 24/100 [02:44<12:10,  9.62s/it]

[I 2026-06-08 17:51:30,503] Trial 23 pruned. Trial was pruned at iteration 100.

Best trial: 13. Best value: 0.172547:  25%|██▌       | 25/100 [02:57<13:09, 10.52s/it]

[I 2026-06-08 17:51:43,141] Trial 24 finished with value: 0.1693775749726266 and parameters: {'n_estimators': 1688, 'learning_rate': 0.06986521869697976, 'max_depth': 10, 'min_child_weight': 10, 'subsample': 0.8001987159314662, 'colsample_bytree': 0.7514316324859271, 'gamma': 4.5451539101036875}. Best is trial 13 with value: 0.17254692511824377.

Best trial: 13. Best value: 0.172547:  26%|██▌       | 26/100 [03:02<11:11,  9.08s/it]

[I 2026-06-08 17:51:48,849] Trial 25 pruned. Trial was pruned at iteration 101.

Best trial: 13. Best value: 0.172547:  27%|██▋       | 27/100 [03:08<09:47,  8.04s/it]

[I 2026-06-08 17:51:54,479] Trial 26 finished with value: 0.15873845739564238 and parameters: {'n_estimators': 1837, 'learning_rate': 0.07201311175065324, 'max_depth': 10, 'min_child_weight': 18, 'subsample': 0.9252541921473181, 'colsample_bytree': 0.8657611061596413, 'gamma': 4.132350740189407}. Best is trial 13 with value: 0.17254692511824377.

Best trial: 13. Best value: 0.172547:  28%|██▊       | 28/100 [03:13<08:40,  7.23s/it]

[I 2026-06-08 17:51:59,800] Trial 27 pruned. Trial was pruned at iteration 100.

Best trial: 13. Best value: 0.172547:  29%|██▉       | 29/100 [03:20<08:28,  7.16s/it]

[I 2026-06-08 17:52:06,802] Trial 28 pruned. Trial was pruned at iteration 100.

Best trial: 13. Best value: 0.172547:  30%|███       | 30/100 [03:25<07:22,  6.32s/it]

[I 2026-06-08 17:52:11,162] Trial 29 pruned. Trial was pruned at iteration 100.

Best trial: 13. Best value: 0.172547:  31%|███       | 31/100 [03:28<06:26,  5.60s/it]

[I 2026-06-08 17:52:15,078] Trial 30 pruned. Trial was pruned at iteration 100.

Best trial: 31. Best value: 0.174449:  32%|███▏      | 32/100 [03:37<07:27,  6.58s/it]

[I 2026-06-08 17:52:23,937] Trial 31 finished with value: 0.17444909749374984 and parameters: {'n_estimators': 1706, 'learning_rate': 0.07086531553515282, 'max_depth': 10, 'min_child_weight': 10, 'subsample': 0.8094847710177969, 'colsample_bytree': 0.7673942296646392, 'gamma': 4.584924685029617}. Best is trial 31 with value: 0.17444909749374984.

Best trial: 31. Best value: 0.174449:  33%|███▎      | 33/100 [03:41<06:30,  5.83s/it]

[I 2026-06-08 17:52:28,029] Trial 32 finished with value: 0.1547065853816584 and parameters: {'n_estimators': 1636, 'learning_rate': 0.07273991758355604, 'max_depth': 10, 'min_child_weight': 11, 'subsample': 0.8241569253115746, 'colsample_bytree': 0.7757237454107023, 'gamma': 4.133754434832153}. Best is trial 31 with value: 0.17444909749374984.

Best trial: 33. Best value: 0.176105:  34%|███▍      | 34/100 [03:52<08:05,  7.36s/it]

[I 2026-06-08 17:52:38,956] Trial 33 finished with value: 0.17610501447579624 and parameters: {'n_estimators': 2051, 'learning_rate': 0.0653120539535119, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.9347640035594816, 'colsample_bytree': 0.8330856612566522, 'gamma': 4.632610001567269}. Best is trial 33 with value: 0.17610501447579624.

Best trial: 33. Best value: 0.176105:  35%|███▌      | 35/100 [03:57<07:10,  6.63s/it]

[I 2026-06-08 17:52:43,817] Trial 34 pruned. Trial was pruned at iteration 101.

Best trial: 33. Best value: 0.176105:  36%|███▌      | 36/100 [04:06<07:51,  7.36s/it]

[I 2026-06-08 17:52:52,951] Trial 35 finished with value: 0.17205372731615545 and parameters: {'n_estimators': 1487, 'learning_rate': 0.057321367956058036, 'max_depth': 9, 'min_child_weight': 9, 'subsample': 0.9674143050112185, 'colsample_bytree': 0.8076103276232462, 'gamma': 4.588908683105428}. Best is trial 33 with value: 0.17610501447579624.

Best trial: 33. Best value: 0.176105:  37%|███▋      | 37/100 [04:11<06:50,  6.52s/it]

[I 2026-06-08 17:52:57,505] Trial 36 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  38%|███▊      | 38/100 [04:16<06:08,  5.95s/it]

[I 2026-06-08 17:53:02,108] Trial 37 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  39%|███▉      | 39/100 [04:20<05:44,  5.64s/it]

[I 2026-06-08 17:53:07,053] Trial 38 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  40%|████      | 40/100 [04:26<05:30,  5.51s/it]

[I 2026-06-08 17:53:12,247] Trial 39 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  41%|████      | 41/100 [04:29<04:46,  4.85s/it]

[I 2026-06-08 17:53:15,566] Trial 40 finished with value: 0.13124725393718262 and parameters: {'n_estimators': 2343, 'learning_rate': 0.05219951028485085, 'max_depth': 7, 'min_child_weight': 10, 'subsample': 0.9138311390425778, 'colsample_bytree': 0.8104639116638712, 'gamma': 2.8860797059484495}. Best is trial 33 with value: 0.17610501447579624.

Best trial: 33. Best value: 0.176105:  42%|████▏     | 42/100 [04:38<06:01,  6.23s/it]

[I 2026-06-08 17:53:25,013] Trial 41 finished with value: 0.16800086676561807 and parameters: {'n_estimators': 2062, 'learning_rate': 0.06525806385577962, 'max_depth': 10, 'min_child_weight': 12, 'subsample': 0.941029087357721, 'colsample_bytree': 0.9000880365156304, 'gamma': 4.450810122016367}. Best is trial 33 with value: 0.17610501447579624.

Best trial: 33. Best value: 0.176105:  43%|████▎     | 43/100 [04:43<05:34,  5.87s/it]

[I 2026-06-08 17:53:30,045] Trial 42 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  44%|████▍     | 44/100 [04:50<05:33,  5.95s/it]

[I 2026-06-08 17:53:36,168] Trial 43 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  45%|████▌     | 45/100 [04:55<05:21,  5.85s/it]

[I 2026-06-08 17:53:41,796] Trial 44 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  46%|████▌     | 46/100 [05:01<05:08,  5.71s/it]

[I 2026-06-08 17:53:47,174] Trial 45 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  47%|████▋     | 47/100 [05:07<05:19,  6.02s/it]

[I 2026-06-08 17:53:53,917] Trial 46 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  48%|████▊     | 48/100 [05:16<05:54,  6.82s/it]

[I 2026-06-08 17:54:02,604] Trial 47 finished with value: 0.17490374879944148 and parameters: {'n_estimators': 1093, 'learning_rate': 0.07543687161066231, 'max_depth': 10, 'min_child_weight': 11, 'subsample': 0.7620214652275785, 'colsample_bytree': 0.9580340256459512, 'gamma': 3.682677702169851}. Best is trial 33 with value: 0.17610501447579624.

Best trial: 33. Best value: 0.176105:  49%|████▉     | 49/100 [05:24<06:00,  7.07s/it]

[I 2026-06-08 17:54:10,265] Trial 48 finished with value: 0.1688526493996968 and parameters: {'n_estimators': 667, 'learning_rate': 0.07600440305334313, 'max_depth': 9, 'min_child_weight': 11, 'subsample': 0.761196653121987, 'colsample_bytree': 0.9594723450248723, 'gamma': 3.9271966775343436}. Best is trial 33 with value: 0.17610501447579624.

Best trial: 33. Best value: 0.176105:  50%|█████     | 50/100 [05:28<05:12,  6.24s/it]

[I 2026-06-08 17:54:14,569] Trial 49 finished with value: 0.15986088645797883 and parameters: {'n_estimators': 1060, 'learning_rate': 0.07887063134375427, 'max_depth': 8, 'min_child_weight': 3, 'subsample': 0.7058392308645814, 'colsample_bytree': 0.3809309208475452, 'gamma': 3.380612502668945}. Best is trial 33 with value: 0.17610501447579624.

Best trial: 33. Best value: 0.176105:  51%|█████     | 51/100 [05:34<05:06,  6.26s/it]

[I 2026-06-08 17:54:20,886] Trial 50 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  52%|█████▏    | 52/100 [05:48<06:54,  8.65s/it]

[I 2026-06-08 17:54:35,085] Trial 51 finished with value: 0.17514540295155998 and parameters: {'n_estimators': 1323, 'learning_rate': 0.06782852144492386, 'max_depth': 10, 'min_child_weight': 15, 'subsample': 0.7687228894066093, 'colsample_bytree': 0.9582866120782167, 'gamma': 4.846384321919188}. Best is trial 33 with value: 0.17610501447579624.

Best trial: 33. Best value: 0.176105:  53%|█████▎    | 53/100 [05:57<06:43,  8.59s/it]

[I 2026-06-08 17:54:43,541] Trial 52 pruned. Trial was pruned at iteration 176.

Best trial: 33. Best value: 0.176105:  54%|█████▍    | 54/100 [06:08<07:08,  9.31s/it]

[I 2026-06-08 17:54:54,546] Trial 53 finished with value: 0.17062969593823585 and parameters: {'n_estimators': 886, 'learning_rate': 0.05808735538404584, 'max_depth': 10, 'min_child_weight': 15, 'subsample': 0.7999463726449499, 'colsample_bytree': 0.9883908843557572, 'gamma': 4.999175322753983}. Best is trial 33 with value: 0.17610501447579624.

Best trial: 33. Best value: 0.176105:  55%|█████▌    | 55/100 [06:13<06:04,  8.10s/it]

[I 2026-06-08 17:54:59,818] Trial 54 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  56%|█████▌    | 56/100 [06:18<05:13,  7.14s/it]

[I 2026-06-08 17:55:04,699] Trial 55 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  57%|█████▋    | 57/100 [06:24<04:45,  6.65s/it]

[I 2026-06-08 17:55:10,209] Trial 56 pruned. Trial was pruned at iteration 101.

Best trial: 33. Best value: 0.176105:  58%|█████▊    | 58/100 [06:29<04:23,  6.28s/it]

[I 2026-06-08 17:55:15,626] Trial 57 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  59%|█████▉    | 59/100 [06:33<03:46,  5.52s/it]

[I 2026-06-08 17:55:19,278] Trial 58 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  60%|██████    | 60/100 [06:38<03:35,  5.39s/it]

[I 2026-06-08 17:55:24,469] Trial 59 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  61%|██████    | 61/100 [06:46<03:57,  6.09s/it]

[I 2026-06-08 17:55:32,182] Trial 60 pruned. Trial was pruned at iteration 153.

Best trial: 33. Best value: 0.176105:  62%|██████▏   | 62/100 [06:51<03:42,  5.86s/it]

[I 2026-06-08 17:55:37,501] Trial 61 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  63%|██████▎   | 63/100 [07:00<04:11,  6.81s/it]

[I 2026-06-08 17:55:46,533] Trial 62 finished with value: 0.17110558159954584 and parameters: {'n_estimators': 2043, 'learning_rate': 0.06725278860939199, 'max_depth': 10, 'min_child_weight': 15, 'subsample': 0.9021954748914667, 'colsample_bytree': 0.9569276307361336, 'gamma': 4.561959717752936}. Best is trial 33 with value: 0.17610501447579624.

Best trial: 33. Best value: 0.176105:  64%|██████▍   | 64/100 [07:05<03:50,  6.40s/it]

[I 2026-06-08 17:55:51,986] Trial 63 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  65%|██████▌   | 65/100 [07:10<03:21,  5.77s/it]

[I 2026-06-08 17:55:56,264] Trial 64 finished with value: 0.16371961535706597 and parameters: {'n_estimators': 1829, 'learning_rate': 0.06285601772771744, 'max_depth': 10, 'min_child_weight': 15, 'subsample': 0.8287962388980846, 'colsample_bytree': 0.8845590026418015, 'gamma': 4.616847090106298}. Best is trial 33 with value: 0.17610501447579624.

Best trial: 33. Best value: 0.176105:  66%|██████▌   | 66/100 [07:15<03:07,  5.53s/it]

[I 2026-06-08 17:56:01,242] Trial 65 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  67%|██████▋   | 67/100 [07:21<03:13,  5.86s/it]

[I 2026-06-08 17:56:07,769] Trial 66 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  68%|██████▊   | 68/100 [07:25<02:50,  5.34s/it]

[I 2026-06-08 17:56:12,014] Trial 67 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  69%|██████▉   | 69/100 [07:30<02:38,  5.12s/it]

[I 2026-06-08 17:56:16,611] Trial 68 pruned. Trial was pruned at iteration 100.

Best trial: 33. Best value: 0.176105:  70%|███████   | 70/100 [07:35<02:31,  5.06s/it]

[I 2026-06-08 17:56:21,530] Trial 69 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  71%|███████   | 71/100 [07:43<02:55,  6.06s/it]

[I 2026-06-08 17:56:29,913] Trial 70 finished with value: 0.17691123812947768 and parameters: {'n_estimators': 1266, 'learning_rate': 0.07708419122007407, 'max_depth': 10, 'min_child_weight': 12, 'subsample': 0.8438893019011352, 'colsample_bytree': 0.6518152217337383, 'gamma': 4.2729661681573905}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  72%|███████▏  | 72/100 [07:50<02:58,  6.37s/it]

[I 2026-06-08 17:56:37,012] Trial 71 finished with value: 0.16643260363248838 and parameters: {'n_estimators': 1295, 'learning_rate': 0.0773919375251162, 'max_depth': 10, 'min_child_weight': 13, 'subsample': 0.8543023433834792, 'colsample_bytree': 0.6525372018542106, 'gamma': 4.1783873022431655}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  73%|███████▎  | 73/100 [07:58<03:04,  6.82s/it]

[I 2026-06-08 17:56:44,888] Trial 72 finished with value: 0.16863273166324408 and parameters: {'n_estimators': 952, 'learning_rate': 0.07198910673492961, 'max_depth': 10, 'min_child_weight': 12, 'subsample': 0.8806360780729429, 'colsample_bytree': 0.5680255619188173, 'gamma': 4.648558476147223}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  74%|███████▍  | 74/100 [08:06<03:05,  7.13s/it]

[I 2026-06-08 17:56:52,745] Trial 73 finished with value: 0.16654333866290272 and parameters: {'n_estimators': 2510, 'learning_rate': 0.061311753358477133, 'max_depth': 10, 'min_child_weight': 10, 'subsample': 0.8425402172126373, 'colsample_bytree': 0.5202345555398944, 'gamma': 4.299312063307948}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  75%|███████▌  | 75/100 [08:14<03:04,  7.37s/it]

[I 2026-06-08 17:57:00,660] Trial 74 pruned. Trial was pruned at iteration 153.

Best trial: 70. Best value: 0.176911:  76%|███████▌  | 76/100 [08:24<03:13,  8.07s/it]

[I 2026-06-08 17:57:10,362] Trial 75 finished with value: 0.17051031730802085 and parameters: {'n_estimators': 2084, 'learning_rate': 0.0744324180036049, 'max_depth': 10, 'min_child_weight': 11, 'subsample': 0.815869595674547, 'colsample_bytree': 0.6598872263818926, 'gamma': 4.413461600986794}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  77%|███████▋  | 77/100 [08:33<03:14,  8.45s/it]

[I 2026-06-08 17:57:19,689] Trial 76 finished with value: 0.17369661858318006 and parameters: {'n_estimators': 1089, 'learning_rate': 0.06772783491023657, 'max_depth': 9, 'min_child_weight': 12, 'subsample': 0.9162553728633273, 'colsample_bytree': 0.5190413052574455, 'gamma': 4.754585974994198}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  78%|███████▊  | 78/100 [08:38<02:42,  7.37s/it]

[I 2026-06-08 17:57:24,537] Trial 77 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  79%|███████▉  | 79/100 [08:47<02:44,  7.81s/it]

[I 2026-06-08 17:57:33,389] Trial 78 pruned. Trial was pruned at iteration 248.

Best trial: 70. Best value: 0.176911:  80%|████████  | 80/100 [08:51<02:16,  6.80s/it]

[I 2026-06-08 17:57:37,835] Trial 79 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  81%|████████  | 81/100 [08:58<02:08,  6.76s/it]

[I 2026-06-08 17:57:44,510] Trial 80 finished with value: 0.1697929975623878 and parameters: {'n_estimators': 1047, 'learning_rate': 0.055964341858817435, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.9793607804736546, 'colsample_bytree': 0.3615657539906286, 'gamma': 4.92190017613129}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  82%|████████▏ | 82/100 [09:03<01:54,  6.38s/it]

[I 2026-06-08 17:57:50,001] Trial 81 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  83%|████████▎ | 83/100 [09:10<01:48,  6.40s/it]

[I 2026-06-08 17:57:56,442] Trial 82 finished with value: 0.16574235644041593 and parameters: {'n_estimators': 1572, 'learning_rate': 0.07233248466360337, 'max_depth': 9, 'min_child_weight': 9, 'subsample': 0.9055851771027432, 'colsample_bytree': 0.9103592288980745, 'gamma': 4.598097974753691}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  84%|████████▍ | 84/100 [09:16<01:39,  6.24s/it]

[I 2026-06-08 17:58:02,306] Trial 83 pruned. Trial was pruned at iteration 115.

Best trial: 70. Best value: 0.176911:  85%|████████▌ | 85/100 [09:30<02:11,  8.77s/it]

[I 2026-06-08 17:58:16,964] Trial 84 finished with value: 0.17169403673858866 and parameters: {'n_estimators': 2699, 'learning_rate': 0.07106894091653337, 'max_depth': 10, 'min_child_weight': 14, 'subsample': 0.8040534906704438, 'colsample_bytree': 0.946671974583979, 'gamma': 4.435318368335202}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  86%|████████▌ | 86/100 [09:35<01:46,  7.61s/it]

[I 2026-06-08 17:58:21,886] Trial 85 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  87%|████████▋ | 87/100 [09:40<01:26,  6.62s/it]

[I 2026-06-08 17:58:26,177] Trial 86 finished with value: 0.16380090200436567 and parameters: {'n_estimators': 2807, 'learning_rate': 0.07403594409269106, 'max_depth': 10, 'min_child_weight': 14, 'subsample': 0.8313638475293852, 'colsample_bytree': 0.6276558164395905, 'gamma': 4.404384622595657}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  88%|████████▊ | 88/100 [09:45<01:13,  6.14s/it]

[I 2026-06-08 17:58:31,199] Trial 87 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  89%|████████▉ | 89/100 [09:50<01:06,  6.05s/it]

[I 2026-06-08 17:58:37,050] Trial 88 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  90%|█████████ | 90/100 [09:56<00:59,  5.95s/it]

[I 2026-06-08 17:58:42,768] Trial 89 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  91%|█████████ | 91/100 [10:01<00:51,  5.68s/it]

[I 2026-06-08 17:58:47,803] Trial 90 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  92%|█████████▏| 92/100 [10:12<00:58,  7.28s/it]

[I 2026-06-08 17:58:58,834] Trial 91 finished with value: 0.17192701086123388 and parameters: {'n_estimators': 2976, 'learning_rate': 0.0663752064148041, 'max_depth': 10, 'min_child_weight': 15, 'subsample': 0.919940531037786, 'colsample_bytree': 0.9497350963776791, 'gamma': 4.579002589483713}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  93%|█████████▎| 93/100 [10:18<00:47,  6.74s/it]

[I 2026-06-08 17:59:04,306] Trial 92 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  94%|█████████▍| 94/100 [10:29<00:48,  8.03s/it]

[I 2026-06-08 17:59:15,360] Trial 93 finished with value: 0.17217101457364437 and parameters: {'n_estimators': 2786, 'learning_rate': 0.06941246970462162, 'max_depth': 10, 'min_child_weight': 16, 'subsample': 0.9456195228149331, 'colsample_bytree': 0.8738962082080203, 'gamma': 4.217219833509154}. Best is trial 70 with value: 0.17691123812947768.

Best trial: 70. Best value: 0.176911:  95%|█████████▌| 95/100 [10:34<00:36,  7.34s/it]

[I 2026-06-08 17:59:21,088] Trial 94 pruned. Trial was pruned at iteration 110.

Best trial: 70. Best value: 0.176911:  96%|█████████▌| 96/100 [10:40<00:26,  6.73s/it]

[I 2026-06-08 17:59:26,398] Trial 95 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  97%|█████████▋| 97/100 [10:45<00:19,  6.41s/it]

[I 2026-06-08 17:59:32,057] Trial 96 pruned. Trial was pruned at iteration 113.

Best trial: 70. Best value: 0.176911:  98%|█████████▊| 98/100 [10:49<00:10,  5.49s/it]

[I 2026-06-08 17:59:35,414] Trial 97 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911:  99%|█████████▉| 99/100 [10:54<00:05,  5.47s/it]

[I 2026-06-08 17:59:40,825] Trial 98 pruned. Trial was pruned at iteration 100.

Best trial: 70. Best value: 0.176911: 100%|██████████| 100/100 [11:00<00:00,  6.60s/it]

[I 2026-06-08 17:59:46,417] Trial 99 pruned. Trial was pruned at iteration 100.
Best Val PR-AUC: 0.1769
Best params: {'n_estimators': 1266, 'learning_rate': 0.07708419122007407, 'max_depth': 10, 'min_child_weight': 12, 'subsample': 0.8438893019011352, 'colsample_bytree': 0.6518152217337383, 'gamma': 4.2729661681573905}

## Analyse Study

In [88]:
plot_optimization_history(study)

In [89]:
plot_intermediate_values(study)

In [90]:
plot_parallel_coordinate(study)

In [91]:
plot_param_importances(study)

## Train the model based on optimal params

In [92]:
from xgboost import XGBClassifier
from sklearn.metrics import average_precision_score
import numpy as np

xgb = XGBClassifier(**study.best_params, scale_pos_weight=scale, early_stopping_rounds=50, eval_metric='aucpr', random_state=42)
xgb.fit(X_train_xgb, y_train.numpy(), eval_set=[(X_val_xgb, y_val.numpy())], verbose=100)

val_probs = xgb.predict_proba(X_val_xgb)[:, 1]
prauc = average_precision_score(y_val.numpy(), val_probs)
print(f"XGBoost Val PR-AUC: {prauc:.4f}")

[0]	validation_0-aucpr:0.09066
[100]	validation_0-aucpr:0.16957
[178]	validation_0-aucpr:0.17357
XGBoost Val PR-AUC: 0.1769

On ChallengeData: 0.18635458858763868

Before optimization: 0.1895

In [93]:
import joblib
joblib.dump(xgb, "xgb_model_opt.pkl")

['xgb_model_opt.pkl']

## Create Submission CSV

In [94]:
# Submission
test_probs = xgb.predict_proba(X_test_xgb)[:, 1]

submission = pd.DataFrame({
    "index": range(len(test_x_df)),
    "ID": test_x_df["ID"],
    "fraud_flag": test_probs
})

submission.to_csv("submission_xgb_opt.csv", index=False)
print(submission.head())

   index     ID  fraud_flag
0      0  64707    0.002771
1      1  63919    0.003586
2      2  15664    0.019015
3      3   6626    0.763755
4      4  26766    0.313842